version: '3.6'

services:
  portainer:
    image: portainer/portainer
    volumes:
      - "/home/pi/data/portainer:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - 9000:9000
    networks:
      - default