resources:
- repo: self
queue:
  name: home-automation

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - miflora-mqtt/*
    - config/miflora-mqtt/*

variables:
  imageName: 'geertvdc/miflora-mqtt'

steps:
- script: |
    cd miflora-mqtt
    docker build -f Dockerfile -t "$(imageName):$(Build.BuildId)" .
    docker tag "$(imageName):$(Build.BuildId)" "$(imageName):latest"
    docker push "$(imageName):$(Build.BuildId)"
    docker push "$(imageName):latest"
  displayName: 'Docker Build & Push'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.stagingDirectory)'
  inputs:
    Contents: |
     config/miflora-mqtt/**
     miflora-mqtt/**
    TargetFolder: '$(build.stagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: miflora-mqtt'
  inputs:
    PathtoPublish: '$(build.stagingDirectory)'
    ArtifactName: miflora-mqtt


