version: '3.6'

services:
  miflora-mqtt:
    image: geertvdc/miflora-mqtt
    container_name: miflora-mqtt
    volumes:
      - ./config.livingroom.ini:/miflora-mqtt-daemon/config.ini
    restart: always
    network_mode: "host"
