version: '3.6'

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80"
      - "443:443"
    dns:
      - 127.0.0.1
      - 1.1.1.1
    environment:
      ServerIP: "192.168.1.24"
      WEBPASSWORD: "${PIHOLEWEBPASSWORD}"
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: pihole.vdcruijsen.net
      VIRTUAL_PORT: 80
    cap_add: 
      - NET_ADMIN
    volumes:
      - "/home/pi/config/pihole:/etc/pihole"
      - "/etc/dnsmasq.d:/etc/dnsmasq.d"
      - "/home/pi/pihole/log/pihole.log:/var/log/pihole.log"
    restart: always