version: '3.6'
services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80"
      - "443:443"
    environment:
      ServerIP: "192.168.1.24"
    cap_add: 
      - NET_ADMIN
    volumes:
      - "/home/pi/config/pihole:/etc/pihole"
      - "/etc/dnsmasq.d:/etc/dnsmasq.d"
      - "/home/pi/pihole/log:/var/log"
    network_mode: "host"
    restart: always