version: '3.6'

services:
  mosquitto:
    image: arm32v6/eclipse-mosquitto:1.5.4
    ports:
      - "1883:1883"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/home/pi/mosquitto/config:/mosquitto/config"
      - "/home/pi/mosquitto/log:/mosquitto/log"
      - "/home/pi/mosquitto/data:/mosquitto/data"
    networks:
      - default

  homeassistant:
    image: homeassistant/raspberrypi3-homeassistant:0.82.0
    volumes:
      - "/home/pi/home-assistant/config:/config"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - 8123:8123
    networks:
      - default
