version: '2.3'

services:
  mosquitto:
    image: arm32v6/eclipse-mosquitto:1.5.4
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/home/pi/config/mosquitto:/mosquitto/config"
      - "/home/pi/data/mosquitto/log:/mosquitto/log"
      - "/home/pi/data/mosquitto/data:/mosquitto/data"
    networks:
      - default

  homeassistant:
    image: homeassistant/raspberrypi3-homeassistant:0.84.5
    container_name: home-assistant
    depends_on:
      mosquitto:
        condition: service_started
    volumes:
      - "/home/pi/config/home-assistant:/config"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - 8123:8123
    labels:
      - "traefik.enable=true"
      - "traefik.backend=home-assistant"
      - "traefik.frontend.rule=Host:home.${DOMAINNAME}"
      - "traefik.port=8123"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=vdcruijsen.net"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
    networks:
      - default
      - traefik_proxy

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
