version: '2.3'

services:
  mosquitto:
    image: arm32v6/eclipse-mosquitto:1.5.4
    ports:
      - "1883:1883"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/home/pi/config/mosquitto:/mosquitto/config"
      - "/home/pi/data/mosquitto/log:/mosquitto/log"
      - "/home/pi/data/mosquitto/data:/mosquitto/data"
    networks:
      - default

  homeassistant:
    image: homeassistant/raspberrypi3-homeassistant:0.82.0
    depends_on:
      mosquitto:
        condition: service_started
    volumes:
      - "/home/pi/config/home-assistant:/config"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - 8123:8123
    networks:
      - default
