automation:
  - alias: Cube Shake to turn on
    trigger:
      platform: mqtt
      topic: 'zigbee2mqtt/0x00158d000275dd99'
    condition:
      condition: template
      value_template: '{{ "shake" == trigger.payload_json.action }}'
    action:
      entity_id: light.hall
      service: light.toggle