media_player:
    name: kodi
  - platform: kodi
    host: 192.168.1.24

media_player:
    name: tv
  - platform: samsungtv
    host: 192.168.1.27

media_player:
  - platform: denonavr
    host: 192.168.1.28
    name: denonavr
    timeout: 120
    show_all_sources: True

cast:
  media_player:
  - host: 192.168.1.18