media_player:
  - platform: samsungtv
    name: tv
    host: 192.168.1.27
  - platform: kodi
    name: kodi
    host: 192.168.1.24
  - platform: denonavr
    host: 192.168.1.28
    name: denonavr
    timeout: 120
    show_all_sources: True

cast:
  media_player:
  - host: 192.168.1.11
    name: chromecast