media_player:
  - platform: samsungtv
    name: tv
    host: tv.local
  - platform: kodi
    name: kodi
    host: mediapi.local
  - platform: denonavr
    host: avr.local
    name: denonavr
    timeout: 120
    show_all_sources: True

cast:
  media_player:
  - host: chromecast.local
    name: chromecast