google_assistant:
  project_id: !secret google_project_id 
  api_key: !secret google_apikey
  exposed_domains:
    - switch
    - light
    - group
  entity_config:
    light.0x000d6ffffe1bd2ef_light:
      name: LAMP_HALL
    switch.sonoff_s201:
      name: CHRISTMAS_TREE
      room: LIVINGROOM