google_assistant:
  project_id: !secret google_project_id 
  api_key: !secret google_apikey
  exposed_domains:
    - switch
    - light
    - group
    - media_player
    - script
    - scene
  entity_config:
    #lights
    light.0x000d6ffffe1bd2ef_light:
      name: Hall
      aliases:
        - Hal
        - Hal Lamp
        - Lamp Hal
    switch.sonoff_s201:
      name: Christmas tree
      aliases:
        - Lamp Garage
    light.0x00158d0002c6565f_light:
      name: Garage
      aliases:
        - Lamp Garage
        - Garage Lamp
    light.qubino_zmnhdd1_flush_dimmer_level:
      name: Dining Table
      aliases:
        - Eet tafel
     light.qubino_zmnhdd1_flush_dimmer_level_2:
      name: Lamp Woonkamer
      aliases:
        - Woonkamer
        - Zithoek
        - Kamer
    #media devices
    media_player.denonavr:
      name: Receiver
      aliases:
        - Versterker
