google_assistant:
  project_id: !secret google_project_id 
  api_key: !secret google_apikey
  exposed_domains:
    - switch
    - light
    - group
    - media_player
    - script
    - scene
  entity_config:
    light.0x000d6ffffe1bd2ef_light:
      name: Hall
    switch.sonoff_s201:
      name: Christmas tree
    light.0x00158d0002c6565f_light:
      name: Garage
