automation:

- alias: turn on light when geert is home
  trigger:
    platform: state
    entity_id: device_tracker.androidgeert
    to: 'home'
  action:
    - service: light.turn_on
      data:
        entity_id: light.0x000d6ffffe1bd2ef_light
        brightness: 195
        rgb_color: [0,255,64]
    - delay: '00:03:00'
    - service: light.turn_off
      data:
        entity_id: light.0x000d6ffffe1bd2ef_light
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.dummy2

- alias: turn on light in Garage when motion detected
  trigger:
    platform: state
    entity_id: binary_sensor.garage_motion
    to: 'on'
  condition:
    - condition: state
      value_template: '{{ states.sun.attributes.elevation < 3.5 }}'
  action:
    - service: light.turn_on
      data:
        entity_id: light.garage

- alias: turn off light in Garage when no motion detected
  trigger:
    platform: state
    entity_id: binary_sensor.garage_motion
    to: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id: light.garage

- alias: turn on light in Hall when motion detected
  trigger:
    platform: state
    entity_id: binary_sensor.hall_motion
    to: 'on'
  condition:
    - condition: state
      value_template: '{{ states.sun.attributes.elevation < 3.5 }}'
  action:
    - service: light.turn_on
      data:
        entity_id: light.hall

- alias: turn off light in Hall when no motion detected
  trigger:
    platform: state
    entity_id: binary_sensor.hall_motion
    to: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id: light.hall
