automation:

- alias: turn on light when geert is home
  initial_state: true
  trigger:
    platform: state
    entity_id: device_tracker.androidgeert
    to: 'home'
  action:
    - service: light.turn_on
      data:
        entity_id: binary_sensor.0x00158d0002ea1ba5_occupancy #motionsensor_hall
        brightness: 195
        rgb_color: [0,255,64]
    - delay: '00:03:00'
    - service: light.turn_off
      data:
        entity_id: binary_sensor.0x00158d0002ea1ba5_occupancy #motionsensor_hall
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.dummy2

- alias: turn on light in Garage when motion detected
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.0x00158d0002ea1cdc_occupancy #motionsensor_garage
    to: 'on'
  condition:
    condition: template
    value_template: '{{ states.sun.sun.attributes.elevation < 4 }}'
  action:
    - service: light.turn_on
      data:
        entity_id: light.0x00158d0002c6565f_light #lamp_garage

- alias: turn off light in Garage when no motion detected
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.0x00158d0002ea1cdc_occupancy #motionsensor_garage
    to: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id: light.0x00158d0002c6565f_light #lamp_garage

- alias: turn on light in Hall when motion detected
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.0x00158d0002ea1ba5_occupancy #motionsensor_hall
    to: 'on'
  condition:
    condition: template
    value_template: '{{ states.sun.sun.attributes.elevation < 4 }}'
  action:
    - service: light.turn_on
      data:
        entity_id: light.0x000d6ffffe1bd2ef_light #lamp_hall

- alias: turn off light in Hall when no motion detected
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.0x00158d0002ea1ba5_occupancy #motionsensor_hall
    to: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id: light.0x000d6ffffe1bd2ef_light #lamp_hall
