- alias: Send notification from dummy button
  trigger:
    platform: state
    entity_id: input_boolean.dummy
    to: 'on'
  action:
    # - service: notify.pushover
    #   data:
    #     title: "Dummy notification!"
    #     message: "Honey, I'm home!"
    #     data:
    #       url:
    #       url_title:
    #       sound: pianobar
    #       priority: 0
    #       device: 'Oneplus6Geert'
    - service: notify.telegram
      data:
        #title: '*Send a message*'
        message: "That's an example that _sends_ a *formatted* message with a custom inline keyboard."
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.dummy

- alias: Send notification when Geert is home
  trigger:
    platform: state
    entity_id: device_tracker.androidgeert
    to: 'home'
  action:
    - service: notify.telegram
      data:
        message: '*Geert* is home'

- alias: Send notification when Geert is away
  trigger:
    platform: state
    entity_id: device_tracker.androidgeert
    to: 'not_home'
  action:
    - service: notify.telegram
      data:
        message: '*Geert* is away'

- alias: Send notification when Patty is home
  trigger:
    platform: state
    entity_id: device_tracker.androidpatty
    to: 'home'
  action:
    - service: notify.telegram
      data:
        message: '*Patty* is home'

- alias: Send notification when Patty is away
  trigger:
    platform: state
    entity_id: device_tracker.androidpatty
    to: 'not_home'
  action:
    - service: notify.telegram
      data:
        message: '*Patty* is away'