- alias: Send notification from dummy button
  trigger:
    platform: state
    entity_id: input_boolean.dummy
    to: 'on'
  action:
    - service: notify.telegram_dev
      data:
        message: "example that _sends_ a *formatted* message with a custom inline keyboard."
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.dummy

- alias: Send notification when Geert is home
  trigger:
    platform: state
    entity_id: device_tracker.androidgeert
    to: 'home'
  action:
    - service: notify.telegram_dev
      data:
        message: '*Geert* is home'

- alias: Send notification when Geert is away
  trigger:
    platform: state
    entity_id: device_tracker.androidgeert
    to: 'not_home'
  action:
    - service: notify.telegram_dev
      data:
        message: '*Geert* is away'

- alias: Send notification when Patty is home
  trigger:
    platform: state
    entity_id: device_tracker.androidpatty
    to: 'home'
  action:
    - service: notify.telegram_dev
      data:
        message: '*Patty* is home'

- alias: Send notification when Patty is away
  trigger:
    platform: state
    entity_id: device_tracker.androidpatty
    to: 'not_home'
  action:
    - service: notify.telegram_dev
      data:
        message: '*Patty* is away'