# - alias: Send notification from dummy button
#   initial_state: true
#   trigger:
#     platform: state
#     entity_id: input_boolean.dummy
#     to: 'on'
#   action:
#     - service: notify.telegram_dev
#       data:
#         message: "example that _sends_ a *formatted* message with a custom inline keyboard."
#     - service: input_boolean.turn_off
#       data:
#         entity_id: input_boolean.dummy

- alias: Send notification when Geert is home
  initial_state: true
  trigger:
    platform: state
    entity_id: device_tracker.op6g
    to: 'home'
  action:
    - service: notify.telegram_dev
      data:
        message: '*Geert* is home'

- alias: Send notification when Geert is away
  initial_state: true
  trigger:
    platform: state
    entity_id: device_tracker.op6g
    to: 'not_home'
  action:
    - service: notify.telegram_dev
      data:
        message: '*Geert* is away'

- alias: Send notification when Patty is home
  initial_state: true
  trigger:
    platform: state
    entity_id: device_tracker.android_6d70b33fee1d28b8
    to: 'home'
  action:
    - service: notify.telegram_dev
      data:
        message: '*Patty* is home'

- alias: Send notification when Patty is away
  initial_state: true
  trigger:
    platform: state
    entity_id: device_tracker.android_6d70b33fee1d28b8
    to: 'not_home'
  action:
    - service: notify.telegram_dev
      data:
        message: '*Patty* is away'

# Sync Tasmota devices on startup
- alias: "Sync tasmota state on HA start-up"
  initial_state: true
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "sonoffs/cmnd/state"
        payload: "" 