homeassistant:
  # Name of the location where Home Assistant is running
  name: Hellebaard34
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages

# Enables the frontend
frontend:

# Enables configuration UI
config:

discovery:
  ignore:
    - denonavr

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  reporting: false

# Enables support for tracking state changes over time
history:
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sensor.smartmeter_current_usage
      - sensor.smartmeter_current_return
      - sensor.smartmeter_daily_usage
      - sensor.smartmeter_daily_return
      - sensor.smartmeter_current_usage_w
      - sensor.smartmeter_current_return_w
      - sensor.smartmeter_current 
      - sensor.smartmeter_daily
      - group.smartmeter
      

# View all events in a logbook
logbook:

# Track the sun
sun:

# Dummy switch
input_boolean:
  dummy:
    name: Dummy
    initial: off
    icon: mdi:bell

# MQTT broker
mqtt:
  broker: mosquitto
  discovery: true

telegram_bot:
  - platform: broadcast
    api_key: !secret telegram
    allowed_chat_ids:
      - -308462699

notify:
  - name: pushover
    platform: pushover
    api_key: !secret pushover_apikey
    user_key: !secret pushover_userkey
  - name: telegram
    platform: telegram
    chat_id: -308462699

device_tracker:
  - platform: unifi
    host: 192.168.1.13
    username: !secret unifi_username
    password: !secret unifi_password
    verify_ssl: false
    consider_home: 0:03
    track_new_devices: false
    interval_seconds: 60

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml