
#pushover
pushover_apikey: #{pushover_apikey}#
pushover_userkey: #{pushover_userkey}#

#unifi
unifi_username: #{unifi_username}#
unifi_password: #{unifi_password}#

#location
latitude: #{latitude}#
longitude: #{longitude}#

#telegram
telegram: #{telegram}#

#google
google_project_id: #{google_project_id}#
google_apikey: #{google_apikey}#

#zwave

zwave_key: #{zwave_key}#
