
#pushover
pushover_apikey: #{pushover_apikey}#
pushover_userkey: #{pushover_userkey}#

#unifi
unifi_username: #{unifi_username}#
unifi_password: #{unifi_password}#

#location
latitude: #{latitude}#
longitude: #{longitude}#

#telegram
telegram: #{telegram}#