Geert - Dark:
  ### Main Interface Colors ###
  primary-color: "#A3A3A3"
  light-primary-color: "#C5C5C5"
  primary-background-color: "#272727"
  secondary-background-color: var(--primary-background-color)
  divider-color: "#343434"
  ### Text ###
  primary-text-color: "#FFFFFD"
  secondary-text-color: "#87BF50"
  text-primary-color: "#FFFFFF"
  disabled-text-color: "#A3A3A3"
  ### Sidebar Menu ###
  sidebar-icon-color: "#A3A3A3"
  sidebar-text-color: "#FFFFFD"
  sidebar-selected-background-color: var(--primary-background-color)
  sidebar-selected-icon-color: "#87BF50"
  sidebar-selected-text-color: var(--sidebar-selected-icon-color)
  ### States and Badges ###
  state-icon-color: "#87BF50"
  state-icon-active-color: "#F7AA1C"
  state-icon-unavailable-color: var(--disabled-text-color)
  ### Sliders ###
  paper-slider-knob-color: "#87BF50"
  paper-slider-knob-start-color: var(--paper-slider-knob-color)
  paper-slider-pin-color: var(--paper-slider-knob-color)
  paper-slider-active-color: var(--paper-slider-knob-color)
  paper-slider-secondary-color: var(--light-primary-color)
  ### Labels ###
  label-badge-background-color: "#575757"
  label-badge-text-color: "#FFFFFD"
  label-badge-red: "#575757"
  ### Cards ###
  paper-card-background-color: "#2D2D2D"
  paper-listbox-background-color: var(--primary-background-color)
  ### Toggles ###
  paper-toggle-button-checked-button-color: "#87BF50"
  paper-toggle-button-checked-bar-color: "#598330"
  paper-toggle-button-unchecked-button-color: "#A3A3A3"
  paper-toggle-button-unchecked-bar-color: "#6F6F6F"
  ### Table row ###
  table-row-background-color: var(--primary-background-color)
  table-row-alternative-background-color: var(--secondary-background-color)

Dark - Blue:
  ### Main Interface Colors ###
  primary-color: "#2F7EFD"
  light-primary-color: "#6FA6FE"
  primary-background-color: "#1F1F28"
  secondary-background-color: var(--primary-background-color)
  divider-color: "#2F2F3D"
  ### Text ###
  primary-text-color: "#FFFFFF"
  secondary-text-color: "#6FA6FE"
  text-primary-color: "#FFFFFF"
  disabled-text-color: "#4E4E66"
  ### Sidebar Menu ###
  sidebar-icon-color: "#B6B6C1"
  sidebar-text-color: "#F1F1F1"
  sidebar-selected-background-color: var(--primary-background-color)
  sidebar-selected-icon-color: "#6FA6FE"
  sidebar-selected-text-color: var(--sidebar-selected-icon-color)
  ### States and Badges ###
  state-icon-color: "#2F7EFD"
  state-icon-active-color: "#FBCD41"
  state-icon-unavailable-color: var(--disabled-text-color)
  ### Sliders ###
  paper-slider-knob-color: "#2F7EFD"
  paper-slider-knob-start-color: var(--paper-slider-knob-color)
  paper-slider-pin-color: var(--paper-slider-knob-color)
  paper-slider-active-color: var(--paper-slider-knob-color)
  paper-slider-secondary-color: var(--light-primary-color)
  ### Labels ###
  label-badge-background-color: "#23232E"
  label-badge-text-color: "#F1F1F1"
  label-badge-red: "#6FA6FE"
  ### Cards ###
  paper-card-background-color: "#23232E"
  paper-listbox-background-color: var(--primary-background-color)
  ### Toggles ###
  paper-toggle-button-checked-button-color: "#2F7EFD"
  paper-toggle-button-checked-bar-color: "#6FA6FE"
  paper-toggle-button-unchecked-button-color: var(--paper-toggle-button-checked-button-color)
  paper-toggle-button-unchecked-bar-color: "#3E4756"
  ### Table row ###
  table-row-background-color: var(--primary-background-color)
  table-row-alternative-background-color: var(--secondary-background-color)

Light - Blue:
  ### Main Interface Colors ###
  primary-color: "#2F7EFD"
  light-primary-color: "#6FA6FE"
  primary-background-color: "#FEFEFE"
  secondary-background-color: var(--primary-background-color)
  divider-color: "#E0E2EA"
  ### Text ###
  primary-text-color: "#4D5575"
  secondary-text-color: "#2F7EFD"
  text-primary-color: "#FFFFFF"
  disabled-text-color: "#A6B0BF"
  ### Sidebar Menu ###
  sidebar-icon-color: "#818AAC"
  sidebar-text-color: var(--sidebar-icon-color)
  sidebar-selected-background-color: var(--primary-background-color)
  sidebar-selected-icon-color: "#6FA6FE"
  sidebar-selected-text-color: var(--sidebar-selected-icon-color)
  ### States and Badges ###
  state-icon-color: "#2F7EFD"
  state-icon-active-color: "#FBCD41"
  state-icon-unavailable-color: var(--disabled-text-color)
  ### Sliders ###
  paper-slider-knob-color: "#2F7EFD"
  paper-slider-knob-start-color: var(--paper-slider-knob-color)
  paper-slider-pin-color: var(--paper-slider-knob-color)
  paper-slider-active-color: var(--paper-slider-knob-color)
  paper-slider-secondary-color: var(--light-primary-color)
  ### Labels ###
  label-badge-background-color: "#F8FAF9"
  label-badge-text-color: "#4D5575"
  label-badge-red: "#6FA6FE"
  ### Cards ###
  paper-card-background-color: "#FCFCFC"
  paper-listbox-background-color: var(--primary-background-color)
  ### Toggles ###
  paper-toggle-button-checked-button-color: "#2F7EFD"
  paper-toggle-button-checked-bar-color: "#6FA6FE"
  paper-toggle-button-unchecked-button-color: var(--paper-toggle-button-checked-button-color)
  paper-toggle-button-unchecked-bar-color: "#BFC6D1"
  ### Table row ###
  table-row-background-color: var(--primary-background-color)
  table-row-alternative-background-color: var(--secondary-background-color)