resources:  
  - url: /local/plan-coordinates.js?v=1
    type: js

title: Hellebaard 34
views:
  - title: Floor plan
    icon: mdi:floor-plan
    cards:   
      - id: 0.1
        type: vertical-stack
        cards: 
          - type: custom:plan-coordinates                    
          - type: picture-elements
            image: /local/images/ground-floor.png?v=1
            #title: Begane grond
            elements:
            
            #flower 1
            - type: icon
              icon: mdi:flower
              tap_action: navigate
              navigation_path: /lovelace/0
              style: {color: '#00aa00', left: 66%, top: 61%}
            - type: state-label
              entity: sensor.plant_living_tv_1_moisture
              style: {color: '#ffffff', left: 60%, top: 61%}

            #flower2
            - type: icon
              icon: mdi:flower
              tap_action: navigate
              navigation_path: /lovelace/0
              style: {color: '#00aa00', left: 66%, top: 56%}
            - type: state-label
              entity: sensor.plant_living_tv_2_moisture
              style: {color: '#ffffff', left: 60%, top: 56%}

            #flower 3 (currently unused)
            # - type: icon
            #   icon: mdi:flower
            #   tap_action: navigate
            #   navigation_path: /lovelace/0
            #   style: {color: '#00aa00', left: 30%, top: 70%}
            # - type: state-label
            #   entity: sensor.plant_living_diningtable_moisture
            #   style: {color: '#ffffff', left: 24%, top: 70%}

            #Christmas tree
            - type: state-icon
              entity: switch.sonoff_s201
              icon: mdi:pine-tree
              tap_action: 
                action: toggle
                #service: switch.sonoff_s201.toggle
              style: {color: '#00aa00', left: 20%, top: 53%}

            #Light Hallway
            - type: state-icon
              entity: light.0x000d6ffffe1bd2ef_light
              tap_action: 
                action: toggle
              style: {color: '#00aa00', left: 55%, top: 36%}

            #temperature
            - type: state-label
              entity: sensor.plant_living_tv_1_temperature
              style: {color: '#aaaaaa', left: 44%, top: 72%, font-size: 20px}
            #power
            - type: icon
              icon: mdi:flash
              tap_action: navigate
              navigation_path: /lovelace/0
              style: {color: '#e08338', left: 44%, top: 18.5%}
            - type: state-label
              entity: sensor.smartmeter_current_usage_w
              style: {color: '#ffffff', left: 50%, top: 17%, width: 50px}
            - type: state-label
              entity: sensor.smartmeter_daily_total
              style: {color: '#ffffff', left: 50%, top: 20%, width: 50px}
            #solar
            - type: icon
              icon: mdi:solar-power
              tap_action: navigate
              navigation_path: /lovelace/0
              style: {color: '#00aa00', left: 65%, top: 18.5%}
            - type: state-label
              entity: sensor.smartmeter_current_return_w
              style: {color: '#ffffff', left: 72%, top: 17%, width: 50px}
            - type: state-label
              entity: sensor.smartmeter_daily_return_total
              style: {color: '#ffffff', left: 72%, top: 20%, width: 50px}
      - id: 0.2
        type: vertical-stack 
        cards: 
          - type: picture-elements
            image: /local/images/first-floor.png?v=1  
            elements:  
            - type: icon
              icon: mdi:flower
              tap_action: navigate
              navigation_path: /lovelace/0
              style: {color: '#00aa00', left: 66%, top: 61%}  
  - title: power
    icon: mdi:flash
    cards:
      - id: 1
        type: vertical-stack
        title: tmp 
  - title: plants
    icon: mdi:flower
    cards:
      - id: 2
        type: vertical-stack
        title: tmp
  - title: devices
    icon: mdi:monitor-cellphone-star
    cards:
      - id: 3
        type: vertical-stack
        title: tmp
  - title: Settings
    icon: mdi:settings
    cards:
      - id: 4
        type: vertical-stack
        title: tmp