resources:  
  - url: /local/plan-coordinates.js?v=1
    type: js

title: Hellebaard 34
views:
  - title: Floor plan
    icon: mdi:floor-plan
    cards:   
      - id: 0.1
        type: vertical-stack
        cards: 
          - type: custom:plan-coordinates                    
          - type: picture-elements
            image: /local/images/ground-floor.light.png?v=1
            #title: Begane grond
            elements:
            
            #flower 1
            - type: icon
              icon: mdi:flower
              tap_action: navigate
              navigation_path: /lovelace/0
              style: {color: '#00aa00', left: 66%, top: 61%}
            - type: state-label
              entity: sensor.plant_living_tv_1_moisture
              style: {color: '#000000', left: 60%, top: 61%}

            #flower2
            - type: icon
              icon: mdi:flower
              tap_action: navigate
              navigation_path: /lovelace/0
              style: {color: '#00aa00', left: 66%, top: 56%}
            - type: state-label
              entity: sensor.plant_living_tv_2_moisture
              style: {color: '#000000', left: 60%, top: 56%}

            #flower 3 (currently unused)
            # - type: icon
            #   icon: mdi:flower
            #   tap_action: navigate
            #   navigation_path: /lovelace/0
            #   style: {color: '#00aa00', left: 30%, top: 70%}
            # - type: state-label
            #   entity: sensor.plant_living_diningtable_moisture
            #   style: {color: '#000000', left: 24%, top: 70%}

            #Christmas tree
            # - type: state-icon
            #   entity: switch.sonoff_s201
            #   icon: mdi:pine-tree
            #   tap_action: 
            #     action: toggle
            #   style: {left: 20%, top: 53%}

            #Light diningtable
            - type: state-icon
              entity: light.diningtable
              tap_action: 
                action: toggle
              style: {left: 30%, top: 66%}

            #Light Livingroom
            - type: state-icon
              entity: light.livingroom
              tap_action: 
                action: toggle
              style: {left: 55%, top: 66%}

            #Light Hallway
            - type: state-icon
              entity: light.0x000d6ffffe1bd2ef_light
              tap_action: 
                action: toggle
              style: {color: '#00aa00', left: 55%, top: 36%}

            #Light Garage
            - type: state-icon
              entity: light.0x00158d0002c6565f_light
              tap_action: 
                action: toggle
              style: {color: '#00aa00', left: 73%, top: 36%}

            #temperature
            - type: state-label
              entity: sensor.plant_living_tv_1_temperature
              style: {color: '#aaaaaa', left: 44%, top: 72%, font-size: 20px}
            #power
            - type: icon
              icon: mdi:flash
              tap_action: navigate
              navigation_path: /lovelace/0
              style: {color: '#e08338', left: 44%, top: 18.5%}
            - type: state-label
              entity: sensor.smartmeter_current_usage_w
              style: {color: '#000000', left: 50%, top: 17%, width: 50px}
            - type: state-label
              entity: sensor.smartmeter_daily_total
              style: {color: '#000000', left: 50%, top: 20%, width: 50px}
            #solar
            - type: icon
              icon: mdi:solar-power
              tap_action: navigate
              navigation_path: /lovelace/0
              style: {color: '#00aa00', left: 65%, top: 18.5%}
            - type: state-label
              entity: sensor.smartmeter_current_return_w
              style: {color: '#000000', left: 72%, top: 17%, width: 50px}
            - type: state-label
              entity: sensor.smartmeter_daily_return_total
              style: {color: '#000000', left: 72%, top: 20%, width: 50px}
      - id: 0.2
        type: vertical-stack 
        cards: 
          - type: picture-elements
            image: /local/images/first-floor.light.png?v=1  
            elements:  
            - type: icon
              icon: mdi:flower
              tap_action: navigate
              navigation_path: /lovelace/0
              style: {color: '#00aa00', left: 66%, top: 61%}  
  - title: Lampen
    icon: mdi:lightbulb-outline
    cards:
      - type: horizontal-stack
        cards:
          - type: light
            entity: light.diningtable
          - type: light
            entity: light.livingroom
      - type: horizontal-stack
        cards:
          - type: light
            entity: light.garage
          - type: light
            entity: light.hall
  - title: plants
    icon: mdi:flower
    cards:
      - type: plant-status
        entity: plant.plant_living_tv_1
      - type: plant-status
        entity: plant.plant_living_tv_2
  - title: devices
    icon: mdi:monitor-cellphone-star
    cards:
      - type: entities
        entities:
          - entity: media_player.tv
            name: TV
          - entity: media_player.denonavr
            name: Versterker
          - entity: media_player.kodi
            icon: mdi:kodi
            name: Kodi
          - entity: media_player.geert_tv
            icon: mdi:google-chrome
            name: Chromecast
  - title: Settings
    icon: mdi:settings
    cards:
      - type: entities
        title: Automations
        entities: