resources:  
  - url: /local/plan-coordinates.js?v=1
    type: js

title: Hellebaard 34
views:
  - title: Floor plan
    icon: mdi:wrench
    cards:   
      - id: 0
        type: vertical-stack
        cards: 
          - type: custom:plan-coordinates                    
          - type: picture-elements
            image: /local/images/ground-floor.png
            #title: Begane grond
            elements:
            #flowers
            - type: icon
              icon: mdi:flower
              tap_action: navigate
              navigation_path: /lovelace/0
              style: {color: '#00aa00', left: 66%, top: 56%}
            - type: icon
              icon: mdi:flower
              tap_action: navigate
              navigation_path: /lovelace/0
              style: {color: '#00aa00', left: 66%, top: 61%}
            - type: state-label
              entity: sensor.plant_living_tv_1_moisture
              style: {color: '#ffffff', left: 60%, top: 56%}
            - type: state-label
              entity: sensor.plant_living_tv_1_moisture
              style: {color: '#ffffff', left: 60%, top: 61%}
            #temperature
            - type: state-label
              entity: sensor.plant_living_tv_1_temperature
              style: {color: '#aaaaaa', left: 44%, top: 72%, font-size: 20px}
            #power
            - type: icon
              icon: mdi:power-plug
              tap_action: navigate
              navigation_path: /lovelace/0
              style: {color: '#aa0000', left: 44%, top: 18.5%}
            - type: state-label
              entity: sensor.smartmeter_current_usage_w
              style: {color: '#ffffff', left: 52%, top: 17%}
            - type: state-label
              entity: sensor.smartmeter_daily_total
              style: {color: '#ffffff', left: 52%, top: 20%}

      # - id: 1
      #   type: vertical-stack 
      #   cards: 
      #     #- type: custom:plan-coordinates   
      #     - type: picture-elements
      #       image: /local/images/ground-floor.png  
      #       elements:  
      #       - type: icon
      #         icon: mdi:flower
      #         tap_action: navigate
      #         navigation_path: /lovelace/0
      #         style: {color: '#00aa00', left: 66%, top: 61%}   
  - title: plants
    icon: mdi:flower
    cards:
      - id: 1
        type: vertical-stack
        title: tmp
        # cards:                
        #   - type: picture-elements
        #     image: /local/images/ground-floor.png
        #     #title: Begane grond
        #     elements:
        #     - type: icon
        #       icon: mdi:flower
        #       tap_action: navigate
        #       navigation_path: /lovelace/0
        #       style: {color: '#00aa00', left: 66%, top: 56%}
        #     - type: icon
        #       icon: mdi:flower
        #       tap_action: navigate
        #       navigation_path: /lovelace/0
        #       style: {color: '#00aa00', left: 66%, top: 61%}
        #     - type: state-label
        #       entity: sensor.plant_living_tv_1_moisture
        #       style: {color: '#00aa00', left: 10%, top: 10%}
        #     - type: state-label
        #       entity: sensor.plant_living_tv_1_moisture
        #       style: {color: '#FF0000', left: 20%, top: 10%}
