loglevel = "ERROR"

[backends]
[backends.pihole]
  [backends.pihole.servers.pihole]
    url = "http://192.168.1.24"

[frontends]
  [frontends.pihole]
    entryPoints = ["https"]
    backend = "pihole"
  [frontends.pihole.routes.pihole]
    rule = "Host:pihole.vdcruijsen.net"
  [frontends.pihole.auth]
    [frontends.pihole.auth.basic]
      usersFile = "/shared/.htpasswd"
  [frontends.pihole.headers]
    SSLRedirect = true
    STSSeconds = 315360000
    browserXSSFilter = true
    contentTypeNosniff = true
    forceSTSHeader = true
    SSLHost= "vdcruijsen.net"
    STSIncludeSubdomains = true
    STSPreload = true
    frameDeny = true