version: '3.6'

services:
  dsmrdb:
    image: arm32v6/postgres:11-alpine
    container_name: dsmrdb
    volumes:
      - ./dsmrdb:/var/lib/postgresql/data
      - ./dsmrdb_backups:/dsmr/backups
    restart: always
    environment:
      - POSTGRES_USER=dsmrreader
      - POSTGRES_PASSWORD=dsmrreader
      - POSTGRES_DB=dsmrreader
    networks:
      - default

  dsmr:
    image: xirixiz/dsmr-reader-docker:arm32v6-v2.3.0
    container_name: dsmr
    depends_on:
      - dsmrdb
    cap_add:
      - NET_ADMIN    
    links:
      - dsmrdb
    restart: always
    environment:
      - DB_HOST=dsmrdb
      - DSMR_USER=admin
      - DSMR_EMAIL=root@localhost
      - DSMR_PASSWORD=admin
      - VIRTUAL_HOST=localhost
    ports:
      - 7777:80
      - 7779:443
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    labels:
      - "traefik.enable=true"
      - "traefik.backend=dsmr"
      - "traefik.frontend.rule=Host:dsmr.${DOMAINNAME}"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=vdcruijsen.net"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.auth.basic.usersFile=/shared/.htpasswd"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
    networks:
      - default
      - traefik_proxy
    volumes:
      - ${USERDIR}/config/shared:/shared

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge