resources:
- repo: self
queue:
  name: home-automation

trigger:
  branches:
    include:
      - master
  paths:
    include: 
      - unifi

steps:
- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.stagingDirectory)'
  inputs:
    Contents: |
     unifi/**
    TargetFolder: '$(build.stagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: unifi'
  inputs:
    PathtoPublish: '$(build.stagingDirectory)'
    ArtifactName: unifi
