version: '3.6'

services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:arm32v6-dev
    container_name: zigbee2mqtt
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - /home/pi/zigbee2mqtt/data:/app/data
    restart: always
    network_mode: "host"
