version: '3.6'

services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:1.0.1-arm32v6
    container_name: zigbee2mqtt
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - /var/media/home-automation/zigbee2mqtt/data:/app/data
    restart: always
    network_mode: "host"
